# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=MYSQL CORE_RELEASE=4.0

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.0
    - php: 7.0
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.0
    - php: 7.1
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.0
    - php: 7.2
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.0
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 7.0
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.1
    - php: 7.1
      env: DB=MYSQL PDO=1 CORE_RELEASE=4.1


#
#  allow_failures:
#    - php: 7.0

before_install:
  - pip install --user codecov

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover folderperpage/tests

after_success:
    - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
    - cd ~/build/$TRAVIS_REPO_SLUG

    # Upload Coverage to Scrutinizer
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    # Upload test coverage to codecov
    - codecov
