# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - DB=MYSQL CORE_RELEASE=4.5 PHPUNIT_TEST=1

matrix:
  include:
#    - php: 5.6
#      env: DB=MYSQL PDO=1 CORE_RELEASE=4.0
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4.0 PHPCS_TEST=1 PHPUNIT_COVERAGE_TEST=1
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4.1 PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=4.2 PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=4.3 PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL CORE_RELEASE=4.4 PHPUNIT_TEST=1

#  allow_failures:
#    - php: 7.0

before_install:
  - pip install --user codecov

before_script:
  - composer self-update || true
  - composer validate
  - if [[ $CORE_RELEASE == 4.0 ]]; then composer require --no-update silverstripe/installer:4.0.x; fi
  - if [[ $CORE_RELEASE == 4.1 ]]; then composer require --no-update silverstripe/installer:4.1.x; fi
  - if [[ $CORE_RELEASE == 4.2 ]]; then composer require --no-update silverstripe/installer:4.2.x; fi
  - if [[ $CORE_RELEASE == 4.3 ]]; then composer require --no-update silverstripe/installer:4.3.x; fi
  - if [[ $CORE_RELEASE == 4.4 ]]; then composer require --no-update silverstripe/installer:4.4.x; fi
  - if [[ $CORE_RELEASE == 4.5 ]]; then composer require --no-update silverstripe/installer:4.5.x; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover tests/; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
    - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
    - cd ~/build/$TRAVIS_REPO_SLUG

    # Upload Coverage to Scrutinizer
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    # Upload test coverage to codecov
    - codecov
