# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - DB=MYSQL RECIPE_VERSION=4.5.x-dev PHPUNIT_TEST=1

matrix:
  include:
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=4.3.x-dev PHPCS_TEST=1 PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1


before_install:
  - pip install --user codecov

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer self-update || true
  - composer validate
  - composer require silverstripe/recipe-cms:"$RECIPE_VERSION"  --no-update
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --no-update; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
  
script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover tests/; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
    - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
    - cd ~/build/$TRAVIS_REPO_SLUG

    # Upload Coverage to Scrutinizer
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    # Upload test coverage to codecov
    - codecov
