---
Name: folderperpage
After: 'framework/*, cms/*'
---

NetWerkstatt\FolderPerPage\Extensions\RootFolder:
  ignored_classes:
    - SilverStripe\CMS\Model\VirtualPage
    - SilverStripe\ErrorPage\ErrorPage
  create_folder_for_translations: false
  folder_root: 'Articles'


Page:
  extensions:
    - NetWerkstatt\FolderPerPage\Extensions\RootFolder
